# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/icub-tutorials/src/imageProcessing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/icub-tutorials/src/imageProcessing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/icub-tutorials/src/imageProcessing/CMakeFiles /root/icub-tutorials/src/imageProcessing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/icub-tutorials/src/imageProcessing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named findLocation

# Build rule for target.
findLocation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 findLocation
.PHONY : findLocation

# fast build rule for target.
findLocation/fast:
	$(MAKE) -f CMakeFiles/findLocation.dir/build.make CMakeFiles/findLocation.dir/build
.PHONY : findLocation/fast

#=============================================================================
# Target rules for targets named lookAtLocation

# Build rule for target.
lookAtLocation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lookAtLocation
.PHONY : lookAtLocation

# fast build rule for target.
lookAtLocation/fast:
	$(MAKE) -f CMakeFiles/lookAtLocation.dir/build.make CMakeFiles/lookAtLocation.dir/build
.PHONY : lookAtLocation/fast

findLocation.o: findLocation.cpp.o
.PHONY : findLocation.o

# target to build an object file
findLocation.cpp.o:
	$(MAKE) -f CMakeFiles/findLocation.dir/build.make CMakeFiles/findLocation.dir/findLocation.cpp.o
.PHONY : findLocation.cpp.o

findLocation.i: findLocation.cpp.i
.PHONY : findLocation.i

# target to preprocess a source file
findLocation.cpp.i:
	$(MAKE) -f CMakeFiles/findLocation.dir/build.make CMakeFiles/findLocation.dir/findLocation.cpp.i
.PHONY : findLocation.cpp.i

findLocation.s: findLocation.cpp.s
.PHONY : findLocation.s

# target to generate assembly for a file
findLocation.cpp.s:
	$(MAKE) -f CMakeFiles/findLocation.dir/build.make CMakeFiles/findLocation.dir/findLocation.cpp.s
.PHONY : findLocation.cpp.s

lookAtLocation.o: lookAtLocation.cpp.o
.PHONY : lookAtLocation.o

# target to build an object file
lookAtLocation.cpp.o:
	$(MAKE) -f CMakeFiles/lookAtLocation.dir/build.make CMakeFiles/lookAtLocation.dir/lookAtLocation.cpp.o
.PHONY : lookAtLocation.cpp.o

lookAtLocation.i: lookAtLocation.cpp.i
.PHONY : lookAtLocation.i

# target to preprocess a source file
lookAtLocation.cpp.i:
	$(MAKE) -f CMakeFiles/lookAtLocation.dir/build.make CMakeFiles/lookAtLocation.dir/lookAtLocation.cpp.i
.PHONY : lookAtLocation.cpp.i

lookAtLocation.s: lookAtLocation.cpp.s
.PHONY : lookAtLocation.s

# target to generate assembly for a file
lookAtLocation.cpp.s:
	$(MAKE) -f CMakeFiles/lookAtLocation.dir/build.make CMakeFiles/lookAtLocation.dir/lookAtLocation.cpp.s
.PHONY : lookAtLocation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... findLocation"
	@echo "... lookAtLocation"
	@echo "... rebuild_cache"
	@echo "... findLocation.o"
	@echo "... findLocation.i"
	@echo "... findLocation.s"
	@echo "... lookAtLocation.o"
	@echo "... lookAtLocation.i"
	@echo "... lookAtLocation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

